name: Simple workflow

on:
  workflow_dispatch:
  #pull_request:
  
jobs:
  test:
    name: test
    runs-on: macos-latest

    steps:
      - name: извлечь репозиторий из github
        uses: actions/checkout@v3
      
      - name: скачать и установить JAVA
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 20
          
      #- uses: reactivecircus/android-emulator-runner@v2
      #  with:
      #    api-level: 29
      - run: ./gradlew testDebugUnitTest
