name: Simple workflow

on:
  workflow_dispatch:
  #pull_request:
  
jobs:
  test:
    runs-on: macos-latest

    steps:
      - name: checkout
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: gradle wrapper
