name: Simple workflow

on:
  #workflow_dispatch:
  pull_request:
  
jobs:
  test:
    name: test
    runs-on: macos-latest

    steps:
      - name: Извлечь репозиторий из github
        uses: actions/checkout@v3
      
      - name: Скачать и установить JAVA
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17.0.6
      
      - name: Выполнить unit тесты
        run: ./gradlew testDebugUnitTest
          
      - name: Выполнить тесты на эмуляторе
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew connectedCheck
